# Generated by Django 2.2 on 2019-04-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(default='omnivore', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(default='Cretaceous period', max_length=255)),
                ('region', models.CharField(default='Laramidia which is now western North America', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tyrannosaurus Rex', max_length=255)),
                ('estimated_height', models.CharField(default='15 – 20 feet', max_length=255)),
                ('estimated_mass', models.CharField(default='13,000 – 32,000 lbs', max_length=255)),
                ('image', models.CharField(default='dino pic', max_length=400)),
                ('fossil', models.CharField(default='fossil pic', max_length=400)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='dino_app.Diet')),
                ('location', models.ForeignKey(default='Laramidia which is now western North America', on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='dino_app.Location')),
            ],
        ),
    ]
