# Generated by Django 2.2 on 2019-04-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_height', models.IntegerField()),
                ('estimated_mass', models.IntegerField()),
                ('diet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=400)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='dino_app.Location')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='dino_app.Stats')),
            ],
        ),
    ]
